import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dragon Ball Quiz',
  description: 'Generated by create next app',
}

const Header = () => {
  return (
    <header style={headerStyle}>
      <h1 style={{ color:'fff' }}>Dragon Ball Quiz</h1>
    </header>
  );
}

const headerStyle = {
  backgroundColor: '#ff9922', 
  padding: '20px',
  textAlign: 'center',
  fontSize: '30px',
  font: 'helvetica',
};

const Footer = () => {
  return (
    <footer style={footerStyle}>
    </footer>
  );
}

const footerStyle = {
  backgroundColor: '#ff9922', 
  padding: '30px',
  textAlign: 'center',
  fontSize: '30px',
  font: 'helvetica',
  position: 'fixed',
  bottom: '0',
  width: '100%',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer style={footerStyle} />
      </body>
    </html>
  );
}

